# Generated by Django 5.2.4 on 2025-07-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='name',
        ),
        migrations.AddField(
            model_name='librarian',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
